#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Core	
{
	public partial class Chat
	{
		private long _chat_id;
		public virtual long Chat_id
		{
			get
			{
				return this._chat_id;
			}
			set
			{
				this._chat_id = value;
			}
		}
		
		private string _message;
		public virtual string Message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private DateTime? _time;
		public virtual DateTime? Time
		{
			get
			{
				return this._time;
			}
			set
			{
				this._time = value;
			}
		}
		
	}
}
#pragma warning restore 1591
